swagger: '2.0'

info:
  title: ExCELL Broadcasting API v1
  version: 'v1'
  contact:
    name: André Rademacher
    url: http://www.entiretec.com
  description: 'The ExCELL broadcasting service'

schemes:
  - https

basePath: '/api/v1'

produces:
  - application/json

paths:

  /messages:

    post:

      summary: Sends a message via the selected channel to the contactId.
      description: check
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/message'
          required: true
          description: POST body


      responses:

        201:
          description: The message has been successfully transferred to the service provider.

definitions:
  message:
    description: the message object
    properties:
      channel:
        type: string
        description: Currently, only the channel "sms" exists.
      contactId:
        type: string
        description: Identifies the target for the selected channel, e.g. the mobile phone number for the channel "sms".
      content:
        type: string
        description: The content that is sent to the contactId via the selected channel.
      token:
        type: string
        description: Currently used for authentication purposes.

    required:
      - channel
      - contactId
      - content
      - token

          